language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
